// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCXPXPiWndmo1HGCgq2LYcKnUJ8fNwSs',
    appId: '1:1017641487559:web:37231dea088c27540ac2e2',
    messagingSenderId: '1017641487559',
    projectId: 'chupatu-mobile',
    authDomain: 'chupatu-mobile.firebaseapp.com',
    storageBucket: 'chupatu-mobile.firebasestorage.app',
    measurementId: 'G-5LVS88PXJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZJVscysuEYm0b5wNvqNJece-R_qVUI8',
    appId: '1:1017641487559:android:c336fba5d9c43c800ac2e2',
    messagingSenderId: '1017641487559',
    projectId: 'chupatu-mobile',
    storageBucket: 'chupatu-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75TFA47kr_YQK3G4onGAhqB5hcJX5D_c',
    appId: '1:1017641487559:ios:30f496bd28c2b0000ac2e2',
    messagingSenderId: '1017641487559',
    projectId: 'chupatu-mobile',
    storageBucket: 'chupatu-mobile.firebasestorage.app',
    iosBundleId: 'com.example.chupatuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75TFA47kr_YQK3G4onGAhqB5hcJX5D_c',
    appId: '1:1017641487559:ios:30f496bd28c2b0000ac2e2',
    messagingSenderId: '1017641487559',
    projectId: 'chupatu-mobile',
    storageBucket: 'chupatu-mobile.firebasestorage.app',
    iosBundleId: 'com.example.chupatuMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCXPXPiWndmo1HGCgq2LYcKnUJ8fNwSs',
    appId: '1:1017641487559:web:5d3f0766e095075b0ac2e2',
    messagingSenderId: '1017641487559',
    projectId: 'chupatu-mobile',
    authDomain: 'chupatu-mobile.firebaseapp.com',
    storageBucket: 'chupatu-mobile.firebasestorage.app',
    measurementId: 'G-QQXP2EJ0EQ',
  );
}
